stages:
  - mirror

mirror_to_github:
  stage: mirror
  image: alpine:latest
  tags:
    - dockered
  variables:
    GIT_DEPTH: "0"
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
  script:
    - apk add --no-cache git ca-certificates
    - git config --global user.email "ci@gitlab"
    - git config --global user.name "GitLab CI"
    - git remote add github https://oauth2:${GITHUB_TOKEN}@github.com/CultureLinux/pve-automator.git
    - git fetch --all
    - git push github HEAD:refs/heads/main
    - git push github --tags